server:
  port: 9591

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/macy_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Saketh1@
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
spring.cloud:
    gcp:
      project-id: macy-gcp-2022
      credentials:
        #location: file:[src/main/resources/macy-gcp-2022-ff5099601b3d.json]
        #file:[C:\Users\UK64512\Desktop\GoogleGCPCrdentials\macy-gcp-2022-ff5099601b3d.json] 
        location: file:C:\Users\UK64512\Desktop\GoogleGCPCrdentials\macy-gcp-2022-ff5099601b3d.json


